import 'package:flutter/material.dart';
import 'package:the_menu/models/meal.dart';

import 'category.dart';

const List<Category> categoriesMock = [
  Category(
      id: 'c1',
      title: 'Italian',
      color: Colors.purple,
      imagePath: 'assets/images/categories/italian.jpg'),
  Category(
      id: 'c2',
      title: "Snacks",
      color: Colors.red,
      imagePath: 'assets/images/categories/snacks.jpg'),
  Category(
      id: 'c3',
      title: 'Hamburgers',
      color: Colors.orange,
      imagePath: 'assets/images/categories/hamburger.jpg'),
  Category(
      id: 'c4',
      title: 'German',
      color: Color.fromARGB(255, 180, 47, 14),
      imagePath: 'assets/images/categories/german.jpg'),
  Category(
      id: 'c5',
      title: 'Fit',
      color: Colors.deepOrange,
      imagePath: 'assets/images/categories/fit.jpg'),
  Category(
      id: 'c6',
      title: 'Exotic',
      color: Colors.green,
      imagePath: 'assets/images/categories/exotic.jpg'),
  Category(
      id: 'c7',
      title: 'Breakfast',
      color: Colors.lightBlue,
      imagePath: 'assets/images/categories/breakfast.jpg'),
  Category(
      id: 'c8',
      title: 'Asian',
      color: Colors.lightGreen,
      imagePath: 'assets/images/categories/asian.jpg'),
  Category(
      id: 'c9',
      title: 'French',
      color: Colors.pink,
      imagePath: 'assets/images/categories/french.jpg'),
  Category(
      id: 'c10',
      title: 'Tropical',
      color: Colors.teal,
      imagePath: 'assets/images/categories/tropical.jpg'),
];

const List<Meal> mockMeals = [
  Meal(
    id: 'm1',
    name: 'Spaghetti Carbonara',
    price: 12.99,
    imagePath: 'images/meals/spaghetti_carbonara.jpg',
    description: 'Classic Italian pasta dish with bacon and eggs.',
    durationInMinutes: 30,
    categoriesIds: ['c1', 'c5'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm2',
    name: 'Hawaiian Pizza',
    price: 10.99,
    imagePath: 'images/meals/hawaiian_pizza.jpg',
    description: 'Delicious pizza with ham and pineapple.',
    durationInMinutes: 25,
    categoriesIds: ['c1', 'c6'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm3',
    name: 'Chicken Caesar Salad',
    price: 9.99,
    imagePath: 'images/meals/caesar_salad.jpg',
    description: 'Fresh salad with grilled chicken and Caesar dressing.',
    durationInMinutes: 15,
    categoriesIds: ['c5', 'c9'],
    isGlutenFree: true,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 1,
  ),
  Meal(
    id: 'm4',
    name: 'Margarita Pizza',
    price: 11.99,
    imagePath: 'images/meals/margarita_pizza.jpg',
    description: 'Classic Italian pizza with tomato, mozzarella, and basil.',
    durationInMinutes: 20,
    categoriesIds: ['c1'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: true,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm5',
    name: 'Vegetable Stir-Fry',
    price: 9.49,
    imagePath: 'images/meals/vegetable_stir_fry.jpg',
    description: 'Healthy stir-fried vegetables with tofu and soy sauce.',
    durationInMinutes: 20,
    categoriesIds: ['c5', 'c8'],
    isGlutenFree: true,
    isDairyFree: true,
    isVeggie: true,
    isVegan: true,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm6',
    name: 'Sushi Platter',
    price: 14.99,
    imagePath: 'images/meals/sushi_platter.jpg',
    description: 'Assorted sushi rolls with wasabi and soy sauce.',
    durationInMinutes: 35,
    categoriesIds: ['c8', 'c5'],
    isGlutenFree: false,
    isDairyFree: true,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm7',
    name: 'Chicken Alfredo',
    price: 13.99,
    imagePath: 'images/meals/chicken_alfredo.jpg',
    description: 'Creamy pasta with grilled chicken and Alfredo sauce.',
    durationInMinutes: 30,
    categoriesIds: ['c1'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm8',
    name: 'Tropical Salad',
    price: 8.99,
    imagePath: 'images/meals/tropical_salad.jpg',
    description: 'Fresh Greek salad with feta cheese and olives.',
    durationInMinutes: 15,
    categoriesIds: ['c10', 'c5'],
    isGlutenFree: true,
    isDairyFree: true,
    isVeggie: true,
    isVegan: false,
    servesHowManyPeople: 1,
  ),
  Meal(
    id: 'm9',
    name: 'Beef Tacos',
    price: 10.49,
    imagePath: 'images/meals/beef_tacos.jpg',
    description: 'Tasty beef tacos with salsa and guacamole.',
    durationInMinutes: 20,
    categoriesIds: ['c10', 'c2'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm10',
    name: 'Vegetable Curry',
    price: 11.99,
    imagePath: 'images/meals/vegetable_curry.jpg',
    description: 'Spicy vegetable curry with rice.',
    durationInMinutes: 25,
    categoriesIds: ['c5', 'c6', 'c8'],
    isGlutenFree: true,
    isDairyFree: true,
    isVeggie: true,
    isVegan: true,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm11',
    name: 'German Cake',
    price: 7.99,
    imagePath: 'images/meals/german_cake.jpg',
    description: 'Rich and moist chocolate cake with frosting.',
    durationInMinutes: 40,
    categoriesIds: ['c4'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 4,
  ),
  Meal(
    id: 'm12',
    name: 'Caprese Salad',
    price: 9.49,
    imagePath: 'images/meals/caprese_salad.jpg',
    description: 'Fresh Caprese salad with tomatoes, mozzarella, and basil.',
    durationInMinutes: 10,
    categoriesIds: ['c10'],
    isGlutenFree: true,
    isDairyFree: true,
    isVeggie: true,
    isVegan: false,
    servesHowManyPeople: 1,
  ),
  Meal(
    id: 'm13',
    name: 'Chicken Fajitas',
    price: 12.99,
    imagePath: 'images/meals/chicken_fajitas.jpg',
    description: 'Sizzling chicken fajitas with bell peppers and onions.',
    durationInMinutes: 30,
    categoriesIds: ['c6', 'c2'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm14',
    name: 'Bratwurst with Sauerkraut',
    price: 9.99,
    imagePath: 'images/meals/bratwurst.jpg',
    description: 'Traditional German sausage with sauerkraut and mustard.',
    durationInMinutes: 20,
    categoriesIds: ['c4'],
    isGlutenFree: false,
    isDairyFree: true,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 1,
  ),
  Meal(
    id: 'm15',
    name: 'Wiener Schnitzel',
    price: 14.99,
    imagePath: 'images/meals/wiener_schnitzel.jpg',
    description: 'Crispy breaded veal or pork cutlet, a classic German dish.',
    durationInMinutes: 30,
    categoriesIds: ['c4'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 1,
  ),
  Meal(
    id: 'm16',
    name: 'Pancakes with Maple Syrup',
    price: 7.99,
    imagePath: 'images/meals/pancakes.jpg',
    description: 'Fluffy pancakes served with maple syrup and butter.',
    durationInMinutes: 15,
    categoriesIds: ['c7'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: true,
    isVegan: false,
    servesHowManyPeople: 2,
  ),
  Meal(
    id: 'm17',
    name: 'Omelette with Vegetables',
    price: 8.49,
    imagePath: 'images/meals/omelette.jpg',
    description: 'Light and fluffy omelette with assorted vegetables.',
    durationInMinutes: 20,
    categoriesIds: ['c7'],
    isGlutenFree: true,
    isDairyFree: true,
    isVeggie: true,
    isVegan: false,
    servesHowManyPeople: 1,
  ),
  Meal(
    id: 'm18',
    name: 'Classic Hamburger',
    price: 8.99,
    imagePath: 'images/meals/hamburger.jpg',
    description: 'Juicy beef patty with lettuce, tomato, onion, and ketchup.',
    durationInMinutes: 15,
    categoriesIds: ['c3'],
    isGlutenFree: false,
    isDairyFree: false,
    isVeggie: false,
    isVegan: false,
    servesHowManyPeople: 1,
  ),
];
